### ISSUE TITLE
Netlify Deployment Environment Breaks

### ISSUE THREAD

**Issue by Skillz4Killz** [jlengstorf/gatsby-auth0-app#1]
Hey,

Followed along your livestream and it was great. 

Whenever I try to deploy this to netlify I always get this same error as if the process.env variables are missing or maybe something else is causing it.

![image](https://user-images.githubusercontent.com/23035000/56403556-d3ecb080-622f-11e9-8bbe-6b578d2a7c37.png)

The variables were created on netlify so they should be working ideally.

![image](https://user-images.githubusercontent.com/23035000/56403590-04cce580-6230-11e9-8df2-e9968cb23e7c.png)

**Comment by krismorf** [comment]
use GATSBY_AUTH0_CALLBACK etc... it should work!

GATSBY_ makes the environment variable global
