### ISSUE TITLE
Unfortunately it's broken

### ISSUE THREAD

**Issue by nevotheless** [jlengstorf/gatsby-auth0-app#2]
Heyho, I just followed the stream recording to understand this whole thing and everything worked fine until the last bunch of minutes.

I figured that there're two issues in the final version:

auth.js
```javascript
export const checkSession = callback => {
  const isLoggedIn = localStorage.getItem("isLoggedIn")
  console.log({ isLoggedIn })
  if (isLoggedIn === "false") {
    console.log("Not logged in")
    callback()
    return
  }
  auth.checkSession({}, setSession(callback))
}
```

Here the addition of the `callback()` and `return` statement breaks the app. Whenever the account page is called now it just does login again and redirects back to the callback without logging the user in.

also (a very minor thing):
for the logout process, you set (also in auth.js inside the logout process)
```javascript
auth.logout({
    returnTo: location.href
  })
```
which does work for the production version but `gatsby develop` fails with 
`error  Unexpected use of 'location'  no-restricted-globals`.

**Comment by nevotheless** [comment]
Now i tried using the auth0.js  and the gatsby-browser.js from the store but the same behavior occurs.

Something with `if (!isAuthenticated()) return callback();` isn't working for me. When I'm commenting that out, I can at least login again. But with that in place the `auth0.checkSession({}, setSession(callback));` is never getting called as it seems.

**Comment by erikdstock** [comment]
I also encountered this error. My immediate solution was to add a second local storage value for `isLoggingIn`. I feel like once i have a more holistic understanding I might get a better idea but for now it looks like this:
```ts
/**
 * Automatically re-fetch the session from auth0
 * (Used in wrapRootElement)
 */
export const checkSession = cb => {
  if (!isLoggedIn() && !isLoggingIn()) {
    console.log("checkSession - not logged in")
    cb()
    return
  }
  console.log("checkSession...", isLoggedIn())
  auth0.checkSession({}, setSession(cb))
}

/**
 * Begin the login flow through auth0
 */
export const login = () => {
  if (isBrowser) {
    console.log("login...")
    localStorage.setItem("isLoggingIn", "true")

    auth0.authorize()
  }
}

export const logout = () => {
  console.log("logout...")

  user = {}
  tokens.idToken = null
  tokens.accessToken = null

  const { protocol, host } = window.location
  const returnTo = `${protocol}//${host}`

  localStorage.removeItem("isLoggedIn")
  auth0.logout({ returnTo })
}

// Set tokens (in memory)
const setSession: (cb?: () => void) => Auth0Callback<any> = (cb = () => {}) => (
  err,
  authResult
) => {
  console.log("setSession...")
  if (err) {
    if (err.error === "login_required") {
      login()
    } else {
      throw err
    }
  } else if (authResult && authResult.accessToken && authResult.idToken) {
    tokens.idToken = authResult.idToken
    tokens.accessToken = authResult.accessToken
    auth0.client.userInfo(authResult.accessToken, (error, userProfile) => {
      if (error) {
        throw err
      }
      user = userProfile

      localStorage.removeItem("isLoggingIn")
      localStorage.setItem("isLoggedIn", "true")

      cb()
    })
  }
}

```

**Comment by jlengstorf** [comment]
Sorry I missed this issue!

@amberleyromo sent me this tutorial, which resolves the issue: https://auth0.com/blog/securing-gatsby-with-auth0/ (repo: https://github.com/auth0-blog/gatsby-auth0)

If anyone has time to PR a fix, I'd greatly appreciate it! If not, I'll put this on my todo list for as soon as I have free time.

**Comment by NWRichmond** [comment]
@jlengstorf I think https://github.com/jlengstorf/gatsby-auth0-app/pull/4 fixes this, along with some other bug fixes and enhancements. Hopefully it keeps your to-do list a little lighter!
