### ISSUE TITLE
User gets immediately redirected to Auth0 login page

### ISSUE THREAD

**Issue by lukitroe** [jlengstorf/gatsby-auth0-app#3]
Hi @jlengstorf 
Hi folks!

I've found a little issue in the `gatsby-browser.js` file. Please refer to [line 17](https://github.com/jlengstorf/gatsby-auth0-app/blob/fb6b3fdeb2db066bd10121a9da219c0671362f76/gatsby-browser.js#L17):
In @jlengstorf solution, the method `componentWillMount()` is called. Doing so, redirects the user immediately to Auth0's login page when the root URL (e.g. `http://localhost:8000`) is requested in the browser. This might be the required behaviour. However, if someone wants a landing page (e.g. for some introduction) line 17 must be changed to `componentDidMount()`. After the change, the landing page is shown and the user can read the text firstly (Yes, I'm that optimistic that users read texts), afterwards they click the link in `index.js` [line 7](https://github.com/jlengstorf/gatsby-auth0-app/blob/fb6b3fdeb2db066bd10121a9da219c0671362f76/src/pages/index.js#L7).

Maybe some of you want a landing page in their Gatsby web app. 
PS: I compared this repo with @samjulien [repo](https://github.com/auth0-blog/gatsby-auth0) and found this difference.

@jlengstorf Thank you so so so much for providing this repo and the YouTube Video. It saved me a lot of time!

Best regards,
lukitroe

**Comment by jlengstorf** [comment]
Fixed in #4!
